battle_logs.json is not a valid json file as it stores multiple json objects.
Run logs_analysis.py to get results from the file.